### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by Vovo4k** [AmurOS/AmurOS#10]
когда новый релиз?
- VlaicuSoft

**Comment by bas1c1** [comment]
Скоро

**Comment by bas1c1** [comment]
Когда сурсы на свою оську скинешь тогда и будет :)

**Comment by bas1c1** [comment]
Если ты умный, то тогда кидай свой дискорд будешь помогать нам делать

**Comment by Vovo4k** [comment]
пон я просто тоже делаю оску

**Comment by bas1c1** [comment]
Сейчас новый релиз вышел, и все таки дай свои контакты

**Comment by Vovo4k** [comment]
VeSoft#0715

**Comment by bas1c1** [comment]
Не правильно пишет((

**Comment by Vovo4k** [comment]
> Не правильно пишет((

 Это уже старый акк щас новый кину

**Comment by Vovo4k** [comment]
VeSoft#0133

**Comment by bas1c1** [comment]
отправил запрос
